### ISSUE TITLE
yarn run relay -- --watch causes TypeError: Cannot read property 'some' of undefined error

### ISSUE THREAD

**Issue by bdefore** [apollographql/relay-modern-hello-world#6]
```
→ yarn run relay -- --watch
yarn run v0.23.4
$ relay-compiler --src ./src --schema schema.graphql --watch
TypeError: Cannot read property 'some' of undefined
    at hasWatchmanRootFile (/Users/d4/code/relay-modern-hello-world/node_modules/relay-compiler/bin/relay-compiler:208:29)
    at /Users/d4/code/relay-modern-hello-world/node_modules/relay-compiler/bin/relay-compiler:90:28
    at Generator.next (<anonymous>)
    at step (/Users/d4/code/relay-modern-hello-world/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/d4/code/relay-modern-hello-world/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at F (/Users/d4/code/relay-modern-hello-world/node_modules/core-js/library/modules/_export.js:35:28)
    at /Users/d4/code/relay-modern-hello-world/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at run (/Users/d4/code/relay-modern-hello-world/node_modules/relay-compiler/bin/relay-compiler:126:18)
    at Object.<anonymous> (/Users/d4/code/relay-modern-hello-world/node_modules/relay-compiler/bin/relay-compiler:164:2)
    at __webpack_require__ (/Users/d4/code/relay-modern-hello-world/node_modules/relay-compiler/bin/relay-compiler:33:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I notice from the yarn.lock that our `dev` declaration in `package.json` matches us to react-relay and relay-compiler version 1.0.0-rc.1 ... perhaps this is no longer up to date? I've run on node 6.2.0 and 7.10.0 on macOS.

Relatedly, the README should probably mention you'll need watchman installed.

**Comment by stubailo** [comment]
Mind sending a PR for those improvements if you get it to work?

**Comment by bdefore** [comment]
when i follow the watch step it gives this error which doesn't give me any easy way to debug based on the stack trace

**Comment by airhorns** [comment]
Did you fine folks ever figure out why you were getting this issue?

**Comment by bdefore** [comment]
@airhorns don't remember if i ever resolved this
